### ISSUE TITLE
API count issue / Feature request.

### ISSUE THREAD

**Issue by zizebra** [spinza/esp_mqtt#1]
Not sure if thefar away date was meant to be published as the values for start and end times for loadshedding. Also noted the scipt is not pulling loadshedding info. Any guidance would be appreciated. I am not knowledgeable on python.

![image](https://github.com/spinza/esp_mqtt/assets/4173129/93f6fb7c-8921-46f8-a104-5dd7139db1c9)

**Comment by spinza** [comment]
Have you set your token API in a config.py in the same folder?

**Comment by zizebra** [comment]
> 

Thank you. 50 /50 exhausted my count for the day. Expected to see an error instead the date. 

On another note, would you be able to publish the COCT Current stage and possibly next upcoming stage.  That would be help. So far so good. this has helped me on my OH deployment.

**Comment by spinza** [comment]
I thought it wasn't working.  

If you've hit your API count limit and restart the script after then it has no way to know the current schedule and will report next loadshedding in the future.  The script doesn't save the data.  Once the count is reset it would automatically fetch the data again. 

If you exceed your API count and not restart your script it will just keep the current schedule until it can poll the API again.

The scripts also assumes that it's the only tool using your API and it attempts to spread out the remaining API count over the time left in the day. So it checks how much time is left in the day and how many API calls are left and tries to spread it evenly over the remaining time.

So on average it shoudl call rougly every 30 min (24h/50 calls).

What do you want it to publish?  If in loadshedding it will tell you when it will end, as well as then the next loadshedding will start (and end).  I had given up on tracking stages.  Can you clearly indicate what you want it to publish?

**Comment by zizebra** [comment]
Api Count is working fine.
