### ISSUE TITLE
Service crashes regularly

### ISSUE THREAD

**Issue by zizebra** [spinza/esp_mqtt#2]
![image](https://github.com/spinza/esp_mqtt/assets/4173129/a5564f04-e8af-4619-bd74-7aceab7bf56f)

I have noted that the service crashes every few seconds to minutes. I assume error checking is not happening.

**Comment by spinza** [comment]
Can you share your `config.py` (removing the API token)? 

Mine seems to be up and running ok.

**Comment by zizebra** [comment]
here is my config files

[config_defaults.txt](https://github.com/spinza/esp_mqtt/files/12560726/config_defaults.txt)
[config.txt](https://github.com/spinza/esp_mqtt/files/12560727/config.txt)

**Comment by zizebra** [comment]
something is not working properly on my end. now the script is not pulling start and end times for loadshedding.  the loadshedding stage and nextstage starttime are coming through

**Comment by zizebra** [comment]
some teething issues. but you may need to add more logging. i enabled debugging. and had to add more logging points and found no issue. However during ordeal i also noted that occassionally the FARAWAYDATE is published whenever there is a problem and this is problematic. when there is problem the logic should no publish any value on the problematic component. 
Secondly on the timing, the referesh time is also working rather erratically. Right out of the box with your value of 10 * 60 to give 600 seconds, the polling happens every almost every minute when i change this  to 30 *60 to give 1800, the reference happens on a timeframe that i could  not understand. sometimes 30 minutes sometimes 45 minutes. 

Thanks it got me to learn some python.

**Comment by spinza** [comment]
Can you log one issue at a time so I can help you?  Your config_default file should not be edited. Whatever is specified in config.py overrides config_default.py.

**Comment by zizebra** [comment]
dont worry i have managed to figure out how you wanted it work and where the script is not meeting my needs.

**Comment by spinza** [comment]
I've just tested the following `config.py` with `config_defaults.py` unchanged from what is in the repository.  It works.

```
#!/usr/bin/env python
import logging

#Logging
LOGGING_LEVEL_CONSOLE = logging.INFO
LOGGING_LEVEL_FILE = logging.ERROR
LOGGING_FILE = None

# MQTT
MQTT_HOST = "192.168.10.10"
MQTT_PORT = 1883
MQTT_USERNAME = "XXX"
MQTT_PASSWORD = "XXX"

# ESP API
ESP_API_TOKEN = "XXX"
ESP_AREA_ID = "capetown-8-muizenberg"
ESP_TEST = False

```

**Comment by spinza** [comment]
What do you want to work differently?

**Comment by zizebra** [comment]
So my challenge that i picked is that, loadshedding times regular switches  between the farawaydate and whichever schedule is coming up next. I noticed that in esp.py , the function for updating the values always initializes to farwaydate whenever it runs. That means everytime this function is called and nothing gets changed, the values would have been re-initialized and published on MQTT. I have commented out the reinitialization and so far so good, the switching has stopped.

**Comment by spinza** [comment]
I reinitialise from time to time as sometimes the client starts after the script and causes issues.

If you are using Homie client it should be fine because when we reinitialise we publish that on this feed:
`homie/eskomsepush/$state init`

For me OpenHAB then automatically ignores all values for the device as the device is being reinitialised.  Once the device comes online we publish `homie/eskomsepush/$state ready` and then OpenHAB or any Homie client should then accepting values on the feed again.

If you've manually configured the MQTT feed this will be problem will see what I can do.

**Comment by spinza** [comment]
Actually even when the device (re)initialises it does not forget  the value.  It will only set the FAR_AWAY_DATE when the script starts up.  So the reinitialise should not affect the value.

If you restart the script itself then you should get the behaviour you are seeing.  The intention is for this script to run as a service and not be restarted frequently.

**Comment by spinza** [comment]
I'm happy to sort out any issues you have but a simple reproducible example of the issue you are seeing would help me help you.    If you've edited the code then it's very difficult to help you.

**Comment by zizebra** [comment]
The 2 problems that i noted is that I do see the MQTT published events with farawaydate which breaks my automation and then the second problem is that sometimes the after loadshedding the next loadshedding remains on previous load shedding schedule or it alternates between next schedule and faraway date. Like now, next timeslot is publishing 2-4am

**Comment by zizebra** [comment]
i wrote a comment and deleted it. I have added debug logging statement to see what is generated and againist what is published. That is the only code change at this stage. I will monitor again and see if there is problems may be iam imagining things.

**Comment by spinza** [comment]
I'm using it at home and I have a Amazon Echo integration.  So I get announcements when next loadshedding time changes and when it is 15min away.  I don't get a lot of notifications.  Sometimes when the script is restarted or the whole server is restarted I get something weird but usually it just lets me know as and when the schedule changes or when i'm close to the actual loadshedding.

**Comment by zizebra** [comment]
Since last restart its good. OH had its own quacks and of course, the FARWAYDATE on the end date was a bit problem. I have rewritten my automation rules to cater for the faraway date and seems all is happy. My next loadshedding slot is tomorrow. Its almost beginning to indicate a problem between the chair and the keyboard.

Do you mind adding a 1 hour alert in addition to 15 and 5. In my case, my rule is usually to check 1 hour before and enable grid charging on my inverter if capacity is below 30%

**Comment by spinza** [comment]
I use OH to do the above and don't have issues.  Can add 1h indicator.

**Comment by zizebra** [comment]
I have finally found the culprit. I was beginning to think there was a problem between the chair and keyboard. The values were coming just fine from the your script. However my OH had not using QOS on MQTT all along. So what was happening is that for some strange reason OH would display the last message good MQTT message when its get a new value from the script, it would update to new value and seconds later revert to last saved MQTT message. Solution restarting the MQTT on OH fixes the issue. Dont know what causes this but that was it.  

Your script is working and awesome. Now i dont have to move to Homeassistant.

**Comment by spinza** [comment]
Yeah I think you need to ensure the QOS settings and retention settings are good.  Let me know as I cannot remember what I did to get that right.  You can change the QOS on the script as well.  IF you let me know if I need to update the README I can do that.
